<?xml version="1.0"?>
<package format="3">
  <name>obstacle_tracking</name>
  <version>0.1.0</version>
  <description>Fast C++ multi-object tracking for obstacle detections</description>
  <maintainer email="maintainer@example.com">maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>lshape_fitting</depend>
  <exec_depend>tf2_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <build_depend>rosidl_typesupport_fastrtps_cpp</build_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>rosidl_runtime_py</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
